version: 2
updates:
- package-ecosystem: "pip"
  directory: "/"
  schedule:
    interval: "{{ cookiecutter.get('dependabot_pip_interval', 'monthly') }}"
    day: "sunday"
    time: "00:00"
    timezone: "Europe/London"
{% if include_exists(".github/dependabot/pip/tail.yml") %}
  {{- include(".github/dependabot/pip/tail.yml", indent=2) -}}
{% endif %}
{% if cookiecutter.get("frontend") == "yes" %}
- package-ecosystem: "npm"
  directory: "/"
  schedule:
    interval: "{{ cookiecutter.get('dependabot_npm_interval', 'monthly') }}"
    day: "sunday"
    time: "00:00"
    timezone: "Europe/London"
{% if include_exists(".github/dependabot/npm/tail.yml") %}
  {{- include(".github/dependabot/npm/tail.yml", indent=2) -}}
{% endif %}
{% endif %}
{% if cookiecutter.get("docker") == "yes" %}
- package-ecosystem: "docker"
  directory: "/"
  schedule:
    interval: "{{ cookiecutter.get('dependabot_docker_interval', 'monthly') }}"
    day: "sunday"
    time: "00:00"
    timezone: "Europe/London"
  ignore:
    # Only send PRs for patch versions of Python.
    - dependency-name: "python"
      update-types: [ "version-update:semver-major", "version-update:semver-minor" ]
{% if include_exists(".github/dependabot/docker/tail.yml") %}
  {{- include(".github/dependabot/docker/tail.yml", indent=2) -}}
{% endif %}
{% endif %}
