name: Deploy
concurrency:
  group: deploy
  cancel-in-progress: true
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - '.cookiecutter/*'
      - '.github/*'
      - 'bin/create-db'
      - 'bin/make_python'
      - 'bin/make_template'
      - 'conf/development.ini'
      - 'conf/supervisord-dev.conf'
      - 'docs/*'
      - 'requirements/*'
      - '!requirements/prod.txt'
      - 'tests/*'
      - '**/.gitignore'
      - '.python-version'
      - 'LICENSE'
      - '*.md'
      - 'docker-compose.yml'
      - 'tox.ini'
jobs:
  docker_hub:
    name: Docker Hub
    uses: hypothesis/workflows/.github/workflows/dockerhub.yml@main
    with:
      Application: {% if cookiecutter.get("__docker_hub_application_name") %}{{ cookiecutter.get("__docker_hub_application_name") }}{% else %}{% raw %}${{ github.event.repository.name }}{% endraw %}{% endif +%}
    secrets: inherit
  {% for job_id, environment in include_json(".github/workflows/environments.json", {}).items() %}
  {{ job_id }}:
    name: {{ environment.github_environment_name }}
    needs: [{{ (["docker_hub"] + environment.get("needs", []))|join(", ") }}]
    uses: hypothesis/workflows/.github/workflows/deploy.yml@main
    with:
      operation: deploy
      github_environment_name: {{ environment.get("github_environment_name", job_id) }}
      github_environment_url: {{ environment.github_environment_url }}
      aws_region: {{ environment.aws_region }}
      elasticbeanstalk_application: {{ environment.elasticbeanstalk_application }}
      elasticbeanstalk_environment: {{ environment.elasticbeanstalk_environment }}
      docker_tag: {% raw %}${{ needs.Docker_Hub.outputs.docker_tag }}{% endraw +%}
    secrets: inherit
  {% endfor %}
