name: Slack
on:
  workflow_run:
    workflows: [CI{% if cookiecutter._directory in ['pyapp', 'pyramid-app'] %}, Deploy{% endif %}{{ cookiecutter.get("__slack_notifications_workflows", "") }}]
    types: [completed]
    branches: [main]
jobs:
  on-failure:
    if: {% raw %}${{ github.event.workflow_run.conclusion == 'failure' }}{% endraw +%}
    name: Post to Slack
    uses: hypothesis/workflows/.github/workflows/slack.yml@main
    with:
      payload: |
        channel: "C4K6M7P5E"
        markdown_text: "Failed `{% raw %}${{ github.event.workflow_run.path }}{% endraw %}` run (attempt {% raw %}${{ github.event.workflow_run.run_attempt }}{% endraw %}) on `{% raw %}${{ github.event.workflow_run.head_branch }}{% endraw %}` in `{% raw %}${{ github.event.workflow_run.repository.full_name }}{% endraw %}`: {% raw %}${{ github.event.workflow_run.html_url }}{% endraw %}"
    secrets: inherit
