services:
  {% if cookiecutter.get("postgres") == "yes" %}
  postgres:
    image: postgres:{{ cookiecutter.get("__postgres_version", "11.5-alpine") }}
    ports:
      - "127.0.0.1:{{ cookiecutter['__postgres_port'] }}:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 1s
    {% if include_exists("docker-compose/postgres.yml") %}
      {{- include("docker-compose/postgres.yml", indent=4) -}}
    {% endif %}
  {% endif %}
  {% if include_exists("docker-compose/services.yml") %}
    {{- include("docker-compose/services.yml", indent=2) -}}
  {% endif %}
{% if include_exists("docker-compose/tail.yml") %}
  {{- include("docker-compose/tail.yml") -}}
{% endif %}
