{% if cookiecutter._directory == 'pypackage' %}
[build-system]
requires = ["setuptools>=45", "setuptools_scm[toml]>=6.2"]
build-backend = "setuptools.build_meta"

[project]
dynamic = ["version"]
name = "{{ cookiecutter.slug }}"
description = "{{ cookiecutter.short_description }}"
readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: BSD License",
    "Intended Audience :: Developers",
]
requires-python = ">={{ python_versions()|oldest|pyformat(PyFormats.MAJOR_DOT_MINOR_FMT) }}"
dependencies = [
  {% if cookiecutter.get("postgres") == "yes" %}
  "sqlalchemy",
  "psycopg2",
  {% endif %}
  {% if include_exists("pyproject.toml/dependencies") %}
    {{- include("pyproject.toml/dependencies", indent=4) -}}
  {% endif %}
]

[project.urls]
Repository = "{{ cookiecutter.__github_url }}"
Issues = "{{ cookiecutter.__github_url }}/issues"
Changelog = "{{ cookiecutter.__github_url }}/releases"
{% if include_exists("pyproject.toml/scripts") %}

[project.scripts]
{{ include("pyproject.toml/scripts") -}}
{% elif cookiecutter.get("console_script") == "yes" %}

[project.scripts]
{{ cookiecutter.__entry_point }} = "{{ cookiecutter.package_name }}.cli:cli"
{% endif %}

[tool.setuptools_scm]
{% endif %}
{% if include_exists("pyproject.toml/tail") %}

{{ include("pyproject.toml/tail") -}}
{% endif %}

[tool.pytest.ini_options]
addopts = "-q"
filterwarnings = [
    "error", # Fail the tests if there are any warnings.
    "ignore:^find_module\\(\\) is deprecated and slated for removal in Python 3.12; use find_spec\\(\\) instead$:DeprecationWarning:importlib",
    "ignore:^FileFinder.find_loader\\(\\) is deprecated and slated for removal in Python 3.12; use find_spec\\(\\) instead$:DeprecationWarning:importlib",
    "ignore:^pkg_resources is deprecated as an API:DeprecationWarning:pkg_resources",
    "ignore:^pkg_resources is deprecated as an API:DeprecationWarning:pyramid",
    "ignore:^Deprecated call to .pkg_resources\\.declare_namespace\\('.*'\\).\\.:DeprecationWarning:pkg_resources",
    "ignore:^'cgi' is deprecated and slated for removal in Python 3\\.13$:DeprecationWarning:webob",
    "ignore:^datetime\\.datetime\\.utcnow\\(\\) is deprecated and scheduled for removal in a future version\\.:DeprecationWarning",
    {% if include_exists("pytest/filterwarnings") %}
        {{- include("pytest/filterwarnings", indent=4) -}}
    {% endif %}
]

[tool.pydocstyle]
ignore = [
    # Missing docstrings.
    "D100","D101","D102","D103","D104","D105","D106","D107",

    # "No blank lines allowed after function docstring" conflicts with the
    # Black code formatter which insists on inserting blank lines after
    # function docstrings.
    "D202",

    # "1 blank line required before class docstring" conflicts with another
    # pydocstyle rule D211 "No blank lines allowed before class docstring".
    "D203",

    # "Multi-line docstring summary should start at the first line"
    # and "Multi-line docstring summary should start at the second line".
    # These two rules conflict with each other so you have to disable one of them.
    # How about we disable them both? PEP 257 says either approach is okay:
    #
    # > The summary line may be on the same line as the opening quotes or on
    # > the next line.
    # >
    # > https://peps.python.org/pep-0257/#multi-line-docstrings
    "D212",
    "D213",
{% if include_exists("pydocstyle/ignores") %}

{{ include("pydocstyle/ignores", indent=4) -}}
{% endif %}
]

[tool.coverage.run]
branch = true
parallel = true
source = ["{{ cookiecutter.package_name }}", "tests/unit"]
omit = [
    "*/{{ cookiecutter.package_name }}/__main__.py",
    {% if cookiecutter.get("_directory") == "pyapp" %}
    "*/{{ cookiecutter.package_name }}/app.py",
    {% endif %}
    {% if cookiecutter.get("_directory") == "pyramid-app" and cookiecutter.get("postgres") == "yes" %}
    "*/{{ cookiecutter.package_name }}/scripts/init_db.py",
    {% endif %}
    {% if include_exists("coverage/omit") %}
        {{- include("coverage/omit", indent=4) -}}
    {% endif %}
]

[tool.coverage.paths]
source = ["src", ".tox/*tests/lib/python*/site-packages"]

[tool.coverage.report]
show_missing = true
precision = 2
fail_under = 100.00
skip_covered = true
exclude_also = [
{% if include_exists("coverage/exclude_also") %}
    {{- include("coverage/exclude_also", indent=4) -}}
{% else %}
    # `if TYPE_CHECKING:` blocks are only executed while running mypy.
    "if TYPE_CHECKING:",
{% if include_exists("coverage/exclude_also/tail") %}
    {{- include("coverage/exclude_also/tail", indent=4) -}}
{% endif %}
{% endif %}
]

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
line_length = 88
default_section = "THIRDPARTY"
known_first_party = ["{{ cookiecutter.package_name }}", "tests"]

[tool.pylint.main]
jobs = 0 # Use one process for CPU.

load-plugins = [
    "pylint.extensions.bad_builtin",
    "pylint.extensions.check_elif",
    "pylint.extensions.docparams",
    "pylint.extensions.mccabe",
    "pylint.extensions.overlapping_exceptions",
    "pylint.extensions.redefined_variable_type",
    {% if include_exists("pylint/plugins") %}
        {{- include("pylint/plugins", indent=4) -}}
    {% endif %}
]

# Fail if there are *any* messages from PyLint.
# The letters refer to PyLint's message categories, see
# https://pylint.pycqa.org/en/latest/messages/messages_introduction.html
fail-on = ["C", "E", "F", "I", "R", "W"]

[tool.pylint.messages_control]
ignore-paths=[
{% if include_exists("pylint/ignore-paths") %}
    {{- include("pylint/ignore-paths", indent=4) -}}
{% endif %}
]
enable = [
    "bad-inline-option",
    "deprecated-pragma",
    "useless-suppression",
    "use-symbolic-message-instead",
    "use-implicit-booleaness-not-comparison-to-zero",
    "use-implicit-booleaness-not-comparison-to-string",
    {% if include_exists("pylint/enables") %}
        {{- include("pylint/enables", indent=4) -}}
    {% endif %}
]
disable = [
    # Docstrings are encouraged but we don't want to enforce that everything
    # must have a docstring.
    "missing-docstring",

    # We don't always want to have to put a `:return:` in a docstring.
    "missing-return-doc",

    # We don't always want to have to put an `:rtype:` in a docstring.
    "missing-return-type-doc",

    # We don't want to have to document the type of every parameter with a
    # `:type:` in the docstring.
    "missing-type-doc",

    # We use isort to sort and group our imports, so we don't need PyLint to
    # check them for us.
    "ungrouped-imports",

    # We use Black to format our code automatically, so we don't need PyLint to
    # check formatting for us.
    "line-too-long",

    # We use isort to sort out imports so we don't need PyLint to check import
    # ordering for us.
    "wrong-import-order",

    "too-few-public-methods",

    # Issues to disable this for false positives, disabling it globally in the meantime https://github.com/PyCQA/pylint/issues/214
    "duplicate-code",
{% if include_exists("pylint/disables") %}

{{ include("pylint/disables", indent=4) -}}
{% endif %}
]

good-names = [
    "i", "j", "k", "ex", "Run", "_", # PyLint's default good names.
    "tm", "db", "ai",
    {% if include_exists("pylint/good_names") %}
        {{- include("pylint/good_names", indent=4) -}}
    {% endif %}
]

[tool.pylint.reports]
output-format = "colorized"
score = "no"

[tool.mypy]
allow_untyped_globals = true
error_summary = false
pretty = true
warn_unused_configs = true
warn_redundant_casts = true
warn_unused_ignores = true

disable_error_code = [
    # https://mypy.readthedocs.io/en/stable/error_code_list.html#code-import-untyped
    "import-untyped",
    {% if include_exists("mypy/disables") %}
        {{- include("mypy/disables", indent=4) -}}
    {% endif %}
]
{% if include_exists("mypy/exclude") %}

exclude = [
{{ include("mypy/exclude", indent=4) -}}
]
{% elif include_exists("mypy/exclude/tail") %}

exclude = [
{{ include("mypy/exclude/tail", indent=4) -}}
]
{% endif %}

[[tool.mypy.overrides]]
module = [
{% if include_exists("mypy/ignore_errors_modules") %}
    {{- include("mypy/ignore_errors_modules", indent=2) -}}
{% else %}
  # Don't try to typecheck the tests for now.
  "tests.*",
{% endif %}
{% if include_exists("mypy/ignore_errors_modules/tail") %}
   {{- include("mypy/ignore_errors_modules/tail", indent=2) -}}
{% endif %}
]
ignore_errors = true
{% if include_exists("pyproject.toml") %}

{{ include("pyproject.toml") -}}
{% endif %}
