name: CI
on:
  push:
  workflow_dispatch:
jobs:
  Test_pypackage:
    name: Test pypackage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - name: Install Python 3.7
        uses: actions/setup-python@v4
        with:
          python-version: '3.7'
      - run: python -m pip install cookiecutter tox
      - name: Configure git
        run: |
          git config --global user.name "GitHub Actions CI Workflow"
          git config --global user.email "<>"
      - name: Add .github/scripts to $PATH
        run: realpath .github/scripts/ >> $GITHUB_PATH
      - run: make test-pypackage
  Test_pyapp:
    name: Test pyapp
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: python -m pip install cookiecutter tox
      - name: Configure git
        run: |
          git config --global user.name "GitHub Actions CI Workflow"
          git config --global user.email "<>"
      - name: Add .github/scripts to $PATH
        run: realpath .github/scripts/ >> $GITHUB_PATH
      - run: make test-pyapp
  Test_pyramid-app:
    name: Test pyramid-app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: python -m pip install cookiecutter tox
      - name: Configure git
        run: |
          git config --global user.name "GitHub Actions CI Workflow"
          git config --global user.email "<>"
      - name: Add .github/scripts to $PATH
        run: realpath .github/scripts/ >> $GITHUB_PATH
      - run: make test-pyramid-app
