name: CI
on:
  push:
  workflow_dispatch:
  schedule:
  - cron: '0 1 * * *'
jobs:
  Test_pypackage:
    name: Test pypackage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Install Python 3.8
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'
      - run: python -m pip install cookiecutter 'tox<4'
      - name: Configure git
        run: |
          git config --global user.name "GitHub Actions CI Workflow"
          git config --global user.email "<>"
      - name: Add .github/scripts to $PATH
        run: realpath .github/scripts/ >> $GITHUB_PATH
      - run: make test-pypackage
  Test_pyapp:
    name: Test pyapp
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: python -m pip install cookiecutter 'tox<4'
      - name: Configure git
        run: |
          git config --global user.name "GitHub Actions CI Workflow"
          git config --global user.email "<>"
      - name: Add .github/scripts to $PATH
        run: realpath .github/scripts/ >> $GITHUB_PATH
      - run: make test-pyapp
  Test_pyramid-app:
    name: Test pyramid-app
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15.3-alpine
        ports:
        - 5439:5432
        env:
          POSTGRES_HOST_AUTH_METHOD: trust
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v4
      - name: Install Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: python -m pip install cookiecutter 'tox<4'
      - name: Configure git
        run: |
          git config --global user.name "GitHub Actions CI Workflow"
          git config --global user.email "<>"
      - name: Add .github/scripts to $PATH
        run: realpath .github/scripts/ >> $GITHUB_PATH
      - name: Create test databases
        run: |
          psql -U postgres -h localhost -p 5439 -c 'CREATE DATABASE my_pyramid_app_tests'
          psql -U postgres -h localhost -p 5439 -c 'CREATE DATABASE my_pyramid_app_functests'
      - run: make test-pyramid-app
