name: Slack
on:
  workflow_run:
    workflows: [CI, Update repos]
    types: [completed]
    branches: [main]
jobs:
  on-failure:
    name: Post to Slack
    uses: hypothesis/workflows/.github/workflows/slack.yml@add-slack-workflow
    with:
      channel: "C4K6M7P5E"
      message: "A workflow run failed\n*Repo:* `${{ github.event.repository.full_name }}` (${{ github.event.repository.html_url }})\n*Workflow:* ${{ github.event.workflow.name }} (${{ github.event.workflow.html_url }})\n*Branch:* `${{ github.event.workflow_run.head_branch }}`\n*Commit:* `${{ github.event.workflow_run.head_commit.id }}`\n*Run:* ${{ github.event.workflow_run.html_url }}\n*Conclusion:* ${{ github.event.workflow_run.conclusion }}"
    secrets: inherit
