name: Slack
on:
  workflow_run:
    workflows: [CI, Update repos]
    types: [completed]
    branches: [main]
jobs:
  on-failure:
    name: Post to Slack
    uses: hypothesis/workflows/.github/workflows/slack.yml@add-slack-workflow
    with:
      payload: |
        channel: "C09E7JB47KP"
        markdown_text: "Failed `${{ github.event.workflow_run.path }}` run on `${{ github.event.workflow_run.head_branch }}` in `${{ github.event.workflow_run.repository.full_name }}`: ${{ github.event.workflow_run.html_url }} (run attempt ${{ github.event.workflow_run.run_attempt }})"
    secrets: inherit
