name: Update repos
on:
  workflow_dispatch:
    inputs:
      repos:
        type: string
        default: __all_cookiecuttered_repos__
        description: "Enter a space-separated list of repos to update. For example: 'hypothesis/repo-1 hypothesis/repo-2 hypothesis/repo-3'. By default it will search for and update all cookiecuttered repos in the Hypothesis GitHub organization."
jobs:
  find_repos:
    name: Find repos
    runs-on: ubuntu-latest
    outputs:
      repos: ${{ steps.find_repos.outputs.repos }}
    steps:
      - run: python3.10 -m pip install pipx
      - run: python3.10 -m pipx install "git+https://github.com/hypothesis/gha-token.git"
      - name: Get GitHub token
        id: github_token
        run: echo GITHUB_TOKEN=$(gha-token --app-id 274948 --installation-id 32440510 --private-key "$PRIVATE_KEY") >> $GITHUB_OUTPUT
        env:
          PRIVATE_KEY: ${{ secrets.HYPOTHESIS_GITHUB_APP_PRIVATE_KEY }}
      - uses: actions/checkout@v3
      - name: Find repos
        id: find_repos
        run: |
          if [ "${{ inputs.repos }}" = "__all_cookiecuttered_repos__" ]
          then
            echo "REPOS=$(bin/find_repos | xargs)" >> $GITHUB_OUTPUT
          else
            echo "REPOS=${{ inputs.repos }}" >> $GITHUB_OUTPUT
          fi
        env:
          GITHUB_TOKEN: ${{ steps.github_token.outputs.GITHUB_TOKEN }}
  update_repos:
    name: Update repos
    uses: hypothesis/commando/.github/workflows/commando.yml@main
    needs: find_repos
    with:
      repos: ${{ needs.find_repos.outputs.repos }}
      branch: cookiecutter
      command: tox -e template
      commit_message: Apply updates from cookiecutter
      pr_title: Apply updates from cookiecutter
      pr_body: "Apply the latest updates from [our cookiecutter template](https://github.com/hypothesis/cookiecutters) to this repo."
    secrets:
      HYPOTHESIS_GITHUB_APP_PRIVATE_KEY: ${{ secrets.HYPOTHESIS_GITHUB_APP_PRIVATE_KEY }}
