name: Update repos
on:
  workflow_dispatch:
    inputs:
      repos:
        type: string
jobs:
  find_repos:
    name: Find repos
    runs-on: ubuntu-latest
    outputs:
      repos: ${{ steps.find_repos.outputs.repos }}
    steps:
      - name: Find repos
        id: find_repos
        run: |
          if [ -z "${{ inputs.repos }}" ]
          then
            echo "REPOS=$(gh api -X GET search/repositories --paginate -f 'q=cookiecutter.json in:readme org:hypothesis archived:false' -q '.items | .[] | .full_name' | xargs)" >> $GITHUB_OUTPUT
          else
            echo "REPOS=${{ inputs.repos }}" >> $GITHUB_OUTPUT
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  update_repos:
    name: Update repos
    uses: hypothesis/commando/.github/workflows/commando.yml@main
    needs: find_repos
    with:
      repos: ${{ needs.find_repos.outputs.repos }}
      branch: cookiecutter
      command: tox -e template
      commit_message: Apply updates from cookiecutter
      pr_title: Apply updates from cookiecutter
      pr_body: "Apply the latest updates from [our cookiecutter template](https://github.com/hypothesis/cookiecutters) to this repo."
    secrets:
      HYPOTHESIS_GITHUB_APP_PRIVATE_KEY: ${{ secrets.HYPOTHESIS_GITHUB_APP_PRIVATE_KEY }}
